### PR TITLE
Update hobbit.sh

### PR DESCRIPTION
**Pull request by rheadkid**
# v.1.0.3 (Minor modifications by R.H. 2017)
#	Minor spelling corrections

# v.1.0.2 (Minor modifications by R.H. 2017)
#	Added prompt
#	Added "PRESS ANY KEY TO CONTINUE" where applicable
#	Removed commands to clear the screen between turns

###############
Sorry about all the previous commits that I deleted. {I had to figure out how to work GitHub.)

### CODE REVIEW

**Comment by kastian** [comment]
Merged, thanks.

Sorry for delay, I was in another city.

I'll fix your patch in next commit to less LOC. Look at it.

If you would like to change your nick to full name at the copyright notice just drop me a line

**Comment by rheadkid** [comment]
Your timing was perfect.

If you hadn't been out of town, you would have been subjected to my first 3
pull-requests, which I completely messed up and deleted.

Also, if I did anything that seemed dumb or perhaps even strange, I
apologize. This is the first time I've done this. I registered on GitHub
just to contribute a little to your project.

I do my best to learn everything I can, to make it easier on everyone else
(like you, for instance), and just to know what the heck I'm supposed to be
doing. There is a LOT of documentation concerning forking and patching on
GitHub though, so I know I was probably a pain in the butt to deal with,
but I'm learning, I promise!

Anyway, it doesn't matter to me if I am credited at all. If you'd prefer a
full name, you can put Richard Headkid on it (which is a pseudonym I use
when writing my own Interactive Fiction, by the way, just to be honest). Or
you can leave it as it is. OR if you need my real name on there for legal
purposes, I can supply that too. (I just used the pseudonym because of
game's content. My current employer is kind of funny about the image he
wants his employee's to project.)

I looked at your commit, too, and it looks pretty awesome as far as I'm
concerned. You just taught me the term LOC, but I agree that it looks much
better with less LOC.

I want to thank you for porting the game to BASH, too! I was researching
the best way to port it myself, and lucked out by finding your port. I had
already begun writing a script of my own, which included the ">" prompt, so
I thought maybe everyone would like having a prompt as well, and here we
are.

I also ported the game to Glulx and Zcode (after getting permission from
Fredrik and Johan first). I submitted them to ifarchive.org and
textadventures.co.uk. If you'd like to add them to this, I can upload them.
But if you think the project is better off with just the BASH version, I'd
agree with you there, too.

Lastly (and a noob question, sorry), I should delete my fork now, right? If
I read everything correctly (and if I read the right thing), that appears
to be what I should do.

Thanks.

**Comment by kastian** [comment]
On Tue, Apr 25, 2017 at 10:11:46AM -0700, rheadkid wrote:
> Also, if I did anything that seemed dumb or perhaps even strange, I
> apologize. This is the first time I've done this. I registered on GitHub
> just to contribute a little to your project.
>
> I do my best to learn everything I can, to make it easier on everyone else
> (like you, for instance), and just to know what the heck I'm supposed to be
> doing. There is a LOT of documentation concerning forking and patching on
> GitHub though, so I know I was probably a pain in the butt to deal with,
> but I'm learning, I promise!

No any problems. BTW git and github are great thigs for work and
collaboration, and they cost (not so much) time to learn them. Also
strongly recommend you to look at git book.

> Anyway, it doesn't matter to me if I am credited at all. If you'd prefer a
> full name, you can put Richard Headkid on it (which is a pseudonym I use
> when writing my own Interactive Fiction, by the way, just to be honest). Or
> you can leave it as it is. OR if you need my real name on there for legal
> purposes, I can supply that too. (I just used the pseudonym because of
> game's content. My current employer is kind of funny about the image he
> wants his employee's to project.)

I've done all credits in accordance with GNU recommendations, but you
can do what's better for you.

> I looked at your commit, too, and it looks pretty awesome as far as I'm
> concerned.

Where is a need to duplicate one piece of code thorought all script?

> You just taught me the term LOC, but I agree that it looks much
> better with less LOC.

Lesser LOC -> easier to read -> less bugs :)

> I want to thank you for porting the game to BASH, too! I was researching
> the best way to port it myself, and lucked out by finding your port.

Glad to hear it.

> I had already begun writing a script of my own, which included the
> ">" prompt, so I thought maybe everyone would like having a prompt
> as well, and here we are.

I've only a bunch of original BATs, and no win machine to check them,
so all porting was based on them. And I couldn't remeber if there was
any prompt in win shell. Great that you've fixed this.

> Lastly (and a noob question, sorry), I should delete my fork now, right? If
> I read everything correctly (and if I read the right thing), that appears
> to be what I should do.

As far as I understand github way you need your own fork only if you
send commits to project from time to time (for instance I've
newsbeuter fork, because sometimes I edit russian translation). In
this case it's easier to sync fork with master, make edits, and then
send PR.

Or in case if you thin to make real fork.

> I also ported the game to Glulx and Zcode (after getting permission from
> Fredrik and Johan first). I submitted them to ifarchive.org and
> textadventures.co.uk. If you'd like to add them to this, I can upload them.
> But if you think the project is better off with just the BASH version, I'd
> agree with you there, too.

What about this:
1. I give contributor's rights to my repo (so you'll need no fork but will make directly with my repo) 
2. You push your ports there
3. And you can take githubs releases to submit to any other sites.

**Comment by rheadkid** [comment]
Wow!

Thanks for all that information! I will definitely put it all to good use.

I'm going to find git book as soon as I send this through to you.

I just realized that I didn't credit you at all in the Glulx or Zcode
ports. In my defense though, I started making those from those same BAT
files that you started with before I found your port, and I didn't credit
myself either.

In fact, I just sent off the seventh email to textadventures.co.uk to get
them to change the page's listing to Fredrik and Johan as the authors and
show it under the GPL rather than the CC. Those guys at textadventures were
really helpful, don't get me wrong. It just took a few times for me to
explain everything. (They really wanted to keep the game on their site and
went out of their way to help me get it all set up correctly. (The problem
was that their site automatically shows a submitted game as written by the
person who submitted it's user name, but they fixed it all up to list only
Fredrik and Johan for me.))

Oh, and here are some links (I included the BASH script, source, solution,
license, README, and the Zcode version in the release folder of the Glulxe
version, too.):

Main website for the game (built by Inform 7 and hosted by textadventures):
http://media.textadventures.co.uk/games/LW8O0_0jNUGWCUpMtnqOIQ/Release/index.html

IFDB's page: http://ifdb.tads.org/viewgame?id=qorm9ta4c7tzxzhj

TextAdventures page:
http://textadventures.co.uk/games/view/-k6niu0eteedowj7zp1mna/the-hobbit-the-true-story-redux-directors-cut-2017-port



> *I've only a bunch of original BATs, and no win machine to check them,*
> *so all porting was based on them. And I couldn't remeber if there was**any
> prompt in win shell.*


There was only the DOS prompt, which is what made me want to port the game
to Glulx or BASH in the first place.

Here's what the game looks like in CMD.EXE:


*---------------------------------------------------------------------------------------------------------------------------------------------*


*Tunnel Like Hall*
*You are in your comfortable tunnel like hall. In fact, it's just a dirty
hole in*
*the ground, but to you it's home. Gandalf is working on a nasty spell.
There*
*is a round, green door set in the eastern wall.*
*You can see:*
*A Wooden Chest*
*Thorin, the dwarf*



*C:\Users\kv\Hobbit-DOS>x chest*
*It's a nice piece of wooden workmanship.*
*There's a burning torch inside it. You decide to pick it up.*

*C:\Users\kv\Hobbit-DOS>ask gandalf about map*
*"Oh, that map. There is absolutely nothing special about it at all. I
guess*
*you could have it, if you want it.", Gandalf declares and hands you the
map.*

*C:\Users\kv\Hobbit-DOS>*


*---------------------------------------------------------------------------------------------------------------------------------------------*

*What about this:*


   1. *I give contributor's rights to my repo (so you'll need no fork but
      will make directly with my repo)*
      2. *You push your ports there*
      3. *And you can take githubs releases to submit to any other sites.*

That sounds great, and I appreciate it.

I plan to read git book before making another commit, though. (I hate not
knowing exactly what I'm doing.)


Well, I'm off to study up on GitHub procedure now, before I end up messing
something up on there.

Thanks again for everything!

It is a pleasure corresponding with you!

Best wishes and many thanks,
William
(writing as Richard Headkid)

**Pull request merged**
